### ISSUE TITLE
mismatched types `PgConnectOptions` and `PgConnectOptions` have similar names, but are actually distinct type

### ISSUE THREAD

**Issue by wty92911** [tyrchen/sqlx-db-tester#7]
Below is my code.
```rust
   #[sqlx_database_tester::test(pool(variable = "pool", migrations = "./migrations"))]
    async fn test_register_and_login() {
  }
```
But the compiler error: mismatched types
   --> src/servers/manager_server.rs:163:5
    |
163 |     #[sqlx_database_tester::test(pool(variable = "pool", migrations = "./migrations"))]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     |
    |     expected `PgConnectOptions`, found `sqlx_core::postgres::options::PgConnectOptions`
    |     arguments to this function are incorrect
    |
    = note: `sqlx_core::postgres::options::PgConnectOptions` and `PgConnectOptions` have similar names, but are actually distinct types
note: `sqlx_core::postgres::options::PgConnectOptions` is defined in crate `sqlx_core`

and I dont know why?
Below is my cargo.toml
```toml
[package]
name = "echo"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tonic-build = "0.12.3"
tonic = "0.12.3"
rand = "0.8"
async-stream = "0.3.6"
time = "0.3.37"
log = "0.4.22"
jsonwebtoken = "9.3.0"
chrono = "0.4.39"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"] }
tokio-stream = "0.1.17"
password-hash = "0.5.0"
argon2 = "0.5.3"
bcrypt = "0.16.0"
thiserror = "2.0.11"
serde_yaml = "0.9.34"
env_logger = "0.11.6"
futures = "0.3.31"
sqlx-database-tester = { version = "0.4.2", features = ["runtime-tokio"] }

[build-dependencies]
tonic-build = "*"

```
